from setuptools import setup, find_packages

setup(
    name="vader-ai",
    version="1.0.0",
    description="Darth Vader AI Voice Assistant Platform",
    author="VaderAI Team",
    packages=find_packages(),
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn[standard]>=0.24.0",
        "python-multipart>=0.0.6",
        "openai-whisper>=20231117",
        "sounddevice>=0.4.6",
        "scipy>=1.11.4",
        "gtts>=2.4.0",
        "transformers>=4.35.0",
        "torch>=2.1.0",
        "pydantic>=2.5.0",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-dotenv>=1.0.0",
        "sqlalchemy>=2.0.23",
        "alembic>=1.13.0",
        "websockets>=12.0",
        "numpy>=1.24.0",
        "librosa>=0.10.1",
        "pydub>=0.25.1",
        "requests>=2.31.0",
        "aiofiles>=23.2.1",
        "redis>=5.0.1",
        "celery>=5.3.4",
    ],
    python_requires=">=3.9",
)
